version: 2
updates:
- package-ecosystem: npm
  directory: "/slides/fz-juelich_4-7/index_files/reveal.js-3.3.0.1"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mustache
    versions:
    - 4.2.0
  - dependency-name: socket.io
    versions:
    - 4.0.0
    - 4.0.1
- package-ecosystem: npm
  directory: "/slides/fz-juelich_4-7/index_files/reveal.js-3.3.0.1/plugin/multiplex"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: grunt-cli
    versions:
    - 1.4.1
  - dependency-name: socket.io
    versions:
    - 4.0.0
